/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
     "aws_cognito_region": "us-east-1", // Replace with your AWS region
    "aws_cognito_identity_pool_id": "us-east-1:803444e8-db4a-4fb8-9840-28614c64ff60",
    "aws_user_pools_id": "us-east-1_Gb2aVLndJ",
    "aws_user_pools_web_client_id": "1n6ttn5ou00ok1fqdp7bgi95tq",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "mybucket03512-main",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://4yzsahh25vh7xd7tojj64np27u.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-xsjbt3vyavcehjvz4sfqksdali",
    "aws_access_key_id":"AKIARJSXARKUPW7BVCXQ",
    "aws_secret_access_key":"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"

};


export default awsmobile;
