import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from '../components/NavBar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-montserrat">
        <header>
          <NavBar />
        </header>
        <main>{children}</main>
      </body>
    </html>
  )
}
